root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/mini-gh-sts ./cmd/mini-gh-sts/"
  bin = "./tmp/mini-gh-sts"
  full_bin = "direnv exec . ./tmp/mini-gh-sts"
  include_ext = ["go"]
  include_file = [".envrc"]
  exclude_dir = ["tmp", "dist", "vendor", ".git", ".github"]
  kill_delay = "2s"
  rerun_delay = 500

[log]
  time = true
  main_only = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
