root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o dist/mini-gh-sts ./cmd/mini-gh-sts/main.go"
  bin = "./dist/mini-gh-sts"
  include_ext = ["go"]
  include_file = [".envrc"]
  exclude_dir = ["dist", "vendor", ".git", ".github"]
  send_interrupt = true
  kill_delay = "3s"
  rerun_delay = 500

[log]
  time = true
  main_only = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
