// gen-permissions generates internal/webhook/permissions_gen.go from the
// GitHub REST API OpenAPI spec. Run via:
//
//	go generate ./internal/webhook/...
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"net/http"
	"os"
	"sort"
	"strings"
)

const (
	specURL    = "https://raw.githubusercontent.com/github/rest-api-description/main/descriptions/api.github.com/api.github.com.json"
	schemaName = "app-permissions"
	outputFile = "permissions_gen.go" // relative to the package directory (set by go generate)
)

type openAPISpec struct {
	Components struct {
		Schemas map[string]struct {
			Properties map[string]struct {
				Enum []string `json:"enum"`
			} `json:"properties"`
		} `json:"schemas"`
	} `json:"components"`
}

func main() {
	log.Printf("fetching %s", specURL)
	resp, err := http.Get(specURL) //nolint:noctx
	if err != nil {
		log.Fatalf("fetch spec: %v", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		log.Fatalf("fetch spec: status %d", resp.StatusCode)
	}

	var spec openAPISpec
	if err := json.NewDecoder(resp.Body).Decode(&spec); err != nil {
		log.Fatalf("decode spec: %v", err)
	}

	schema, ok := spec.Components.Schemas[schemaName]
	if !ok {
		log.Fatalf("schema %q not found in spec", schemaName)
	}

	keys := make([]string, 0, len(schema.Properties))
	for k := range schema.Properties {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var lines []string
	for _, k := range keys {
		prop := schema.Properties[k]
		if len(prop.Enum) == 0 {
			continue
		}
		quoted := make([]string, len(prop.Enum))
		for i, v := range prop.Enum {
			quoted[i] = fmt.Sprintf("%q", v)
		}
		lines = append(lines, fmt.Sprintf("\t%q: {%s},", k, strings.Join(quoted, ", ")))
	}

	src := fmt.Sprintf(`// Code generated by tools/gen-permissions. DO NOT EDIT.
// Source: %s
// Schema: components/schemas/%s

package webhook

// validPermissions maps each GitHub App permission name to its allowed values.
var validPermissions = map[string][]string{
%s
}
`, specURL, schemaName, strings.Join(lines, "\n"))

	formatted, err := format.Source([]byte(src))
	if err != nil {
		log.Fatalf("format source: %v", err)
	}

	if err := os.WriteFile(outputFile, formatted, 0o644); err != nil {
		log.Fatalf("write %s: %v", outputFile, err)
	}

	log.Printf("generated %s with %d permissions", outputFile, len(lines))
}
