name: deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: main
    permissions:
      contents: read
      id-token: write

    env:
      IMAGE: asia-northeast1-docker.pkg.dev/yagihash-lab/sts/sts
      GIT_SHA: ${{ github.sha }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: projects/346973490040/locations/global/workloadIdentityPools/github-yagihash-pool/providers/mini-gh-sts-provider
          service_account: mini-gh-sts@yagihash-lab.iam.gserviceaccount.com

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev --quiet

      - name: Build
        run: docker build -t "$IMAGE:$GIT_SHA" .

      - name: Push
        run: docker push "$IMAGE:$GIT_SHA"

      - name: Deploy to Cloud Run
        run: |
          gcloud run services update sts \
            --image "$IMAGE:$GIT_SHA" \
            --region asia-northeast1 \
            --project yagihash-lab
