name: token

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  token:
    strategy:
      matrix:
        num: [1, 2, 3]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: cicd-sensor/cicd-sensor-action@3a3a447ad3668a3e205bf1273f2f2806bbbd30f3 # v0.0.33

      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Test Policy ${{ matrix.num }}
        continue-on-error: true
        id: token
        uses: yagihash/ghmint-action@be57533eef7f69550d06f0c93eede5589158281a # v1.0.0
        with:
          scope: ${{ github.repository }}
          policy: test-policy-${{ matrix.num }}

      - name: Verify token
        continue-on-error: true
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: |
          gh auth status
