name: token

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  token:
    strategy:
      matrix:
        num: [1, 2, 3]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: cicd-sensor/cicd-sensor-action@6511eb44c91d71b2b93d71193b1bf2cb18352f66 # v0.0.38

      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Test Policy ${{ matrix.num }}
        continue-on-error: true
        id: token
        uses: yagihash/ghmint-action@be57533eef7f69550d06f0c93eede5589158281a # v1.0.0
        with:
          scope: ${{ github.repository }}
          policy: test-policy-${{ matrix.num }}

      - name: Verify token
        continue-on-error: true
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: |
          gh auth status
