name: token

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  token:
    strategy:
      matrix:
        num: [1, 2, 3]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: cicd-sensor/cicd-sensor-action@1935de498397aa7b9bf6ac7ca822ddb430a34843 # v0.0.31

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Test Policy ${{ matrix.num }}
        continue-on-error: true
        id: token
        uses: yagihash/ghmint-action@be57533eef7f69550d06f0c93eede5589158281a # v1.0.0
        with:
          scope: ${{ github.repository }}
          policy: test-policy-${{ matrix.num }}

      - name: Verify token
        continue-on-error: true
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
        run: |
          gh auth status
